/**
 * Cohort seed — rebuilds the Kyiv / London / Paris patient roster (62
 * Characters + their NPCs + the 3 City rows) from a versioned snapshot.
 *
 * WHY THIS EXISTS: the cohort was originally generated by one-off LLM
 * scripts that no longer exist in the repo. The data lived ONLY in the prod
 * DB — a DB loss meant the roster was unrecoverable except from backups.
 * This snapshot (seeds/cohort.json, exported from prod) + this idempotent
 * loader make the cohort reproducible: a fresh DB → `npm run seed` → roster
 * restored.
 *
 * IDEMPOTENT & NON-DESTRUCTIVE (mirrors PromptsService's create-only boot):
 *   - Cities  : upsert by key, never overwriting a live weeklyDigest.
 *   - Characters: created only if the slug is missing — an existing row
 *                 (with live admin edits, photoreal avatar in profileText,
 *                 etc.) is left untouched.
 *   - NPCs    : created only for characters that currently have zero NPCs,
 *                 so re-running never duplicates them.
 *
 * Safe to run anytime: fresh DB → full restore; live DB → no-op for what's
 * already there. No LLM calls — pure data.
 *
 * Run: `npm run seed` (loads ../.env for DATABASE_URL) or, inside a
 * container where DATABASE_URL is set, `npx prisma db seed`.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface CohortCity { key: string; lang: string; displayName: string; country: string; }
interface CohortCharacter {
  slug: string; displayName: string; profileText: string; modality: string;
  lang: string; gender: string | null; neighborhood: string | null;
  interests: string | null; cityKey: string | null;
}
interface CohortNpc {
  characterSlug: string; name: string; relation: string; bio: string | null;
  avatarUrl: string | null; tags: string | null; tension: number;
}
interface Cohort { cities: CohortCity[]; characters: CohortCharacter[]; npcs: CohortNpc[]; }

async function main() {
  const cohort: Cohort = JSON.parse(
    readFileSync(join(__dirname, 'seeds', 'cohort.json'), 'utf8'),
  );

  // 1. Cities — upsert by key, leaving any live digest/news intact.
  const cityIdByKey = new Map<string, number>();
  for (const c of cohort.cities) {
    const row = await prisma.city.upsert({
      where: { key: c.key },
      update: {}, // never clobber weeklyDigest / weatherSummary
      create: { key: c.key, lang: c.lang, displayName: c.displayName, country: c.country },
      select: { id: true },
    });
    cityIdByKey.set(c.key, row.id);
  }

  // 2. Characters — create only if the slug is missing.
  let charsCreated = 0, charsSkipped = 0;
  for (const c of cohort.characters) {
    const existing = await prisma.character.findUnique({ where: { slug: c.slug }, select: { id: true } });
    if (existing) { charsSkipped++; continue; }
    await prisma.character.create({
      data: {
        slug: c.slug,
        displayName: c.displayName,
        profileText: c.profileText,
        modality: c.modality,
        lang: c.lang,
        gender: c.gender,
        neighborhood: c.neighborhood,
        interests: c.interests,
        cityId: c.cityKey ? cityIdByKey.get(c.cityKey) ?? null : null,
        createdById: null, // system-owned → visible to all, like the rest of the roster
      },
    });
    charsCreated++;
  }

  // 3. NPCs — group by character; create only for characters with zero NPCs.
  const npcsBySlug = new Map<string, CohortNpc[]>();
  for (const n of cohort.npcs) {
    if (!npcsBySlug.has(n.characterSlug)) npcsBySlug.set(n.characterSlug, []);
    npcsBySlug.get(n.characterSlug)!.push(n);
  }
  let npcsCreated = 0, npcCharsSkipped = 0;
  for (const [slug, npcs] of npcsBySlug) {
    const char = await prisma.character.findUnique({
      where: { slug },
      select: { id: true, _count: { select: { npcs: true } } },
    });
    if (!char) continue; // character not seeded (shouldn't happen)
    if (char._count.npcs > 0) { npcCharsSkipped++; continue; } // already has NPCs
    await prisma.nPC.createMany({
      data: npcs.map((n) => ({
        characterId: char.id,
        name: n.name,
        relation: n.relation,
        bio: n.bio,
        avatarUrl: n.avatarUrl,
        tags: n.tags,
        tension: n.tension,
      })),
    });
    npcsCreated += npcs.length;
  }

  console.log(
    `Seed done: cities=${cohort.cities.length} | ` +
    `characters +${charsCreated} (skipped ${charsSkipped}) | ` +
    `npcs +${npcsCreated} (skipped ${npcCharsSkipped} chars that already had NPCs)`,
  );
}

main()
  .catch((e) => { console.error('Seed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
